<?xml version="1.0" encoding="UTF-8"?>
<module name="" html-dir="" java-package="ngves.asiainfo.core"  initial-class="">
	<service id="ngves/asiainfo/core/core.service" />
	<service id="ngves/asiainfo/core/custom/custom.service" />
	<service id="ngves/asiainfo/core/comment/comment.service" />
	<service id="ngves/asiainfo/core/ticket/ticket.service" />
	<service id="ngves/asiainfo/core/ware/ware.service" />
	<service id="ngves/asiainfo/core/award/award.service" />
	<service id="ngves/asiainfo/core/floor/floor.service" />
</module> 